# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('com.microsoft.azure', 'azure-eventhubs', '2.3.2')
require_jar('com.microsoft.azure', 'qpid-proton-j-extensions', '1.2.4')
require_jar('com.microsoft.azure', 'azure-eventhubs-eph', '2.5.2')
require_jar('com.microsoft.azure', 'azure-storage', '8.6.6')
require_jar('com.google.code.gson', 'gson', '2.10.1')
require_jar('org.apache.qpid', 'proton-j', '0.33.9')
