# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('com.microsoft.azure', 'azure-eventhubs', '3.3.0')
require_jar('com.microsoft.azure', 'qpid-proton-j-extensions', '1.2.4')
require_jar('com.microsoft.azure', 'azure-eventhubs-eph', '3.3.0')
require_jar('com.microsoft.azure', 'azure-storage', '8.6.6')
