# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('com.google.code.gson', 'gson', '2.8.3')
require_jar('org.apache.qpid', 'proton-j', '0.27.1')
require_jar('org.apache.logging.log4j', 'log4j-slf4j-impl', '2.9.1')
require_jar('com.microsoft.azure', 'azure-eventhubs', '1.0.1')
require_jar('com.microsoft.azure', 'azure-eventhubs-eph', '1.0.0')
require_jar('com.microsoft.azure', 'azure-storage', '7.0.0')
require_jar('org.apache.logging.log4j', 'log4j-api', '2.9.1')
